"""Golden behavior-lock tests for blastn/minimap2 output parsing.

Fixtures and expected ``(matches, fragments)`` values were captured from
the pre-consolidation parsers; any field/value drift in the consolidated
parsers must fail these tests.  Per-backend row schemas are locked as-is:
blastn best rows carry ``sequence`` (and ``copy_count`` under
``count_same_copy``) while minimap2 best rows do not.
"""

from __future__ import annotations

from dataclasses import fields, is_dataclass
from pathlib import Path

from gmlst.aligners.blastn import _parse_blast_output
from gmlst.aligners.minimap2 import _parse_paf

LOCI = ["abcZ", "adk", "aroE", "arcC"]


def _blast_row(
    qseqid: str,
    sseqid: str,
    pident: str,
    length: str,
    qlen: str,
    qstart: str,
    qend: str,
    sstart: str,
    send: str,
    bitscore: str,
    sseq: str,
) -> str:
    return "\t".join(
        [
            qseqid,
            sseqid,
            pident,
            length,
            qlen,
            qstart,
            qend,
            sstart,
            send,
            "0.0",
            bitscore,
            sseq,
        ]
    )


def _write_blast_fixture(path: Path) -> None:
    rows = [
        _blast_row(
            "arcC_1",
            "contig1",
            "100.000",
            "480",
            "480",
            "1",
            "480",
            "100",
            "579",
            "900",
            "ACGT" * 120,
        ),
        _blast_row(
            "arcC_1",
            "contig2",
            "99.792",
            "480",
            "480",
            "1",
            "480",
            "500",
            "979",
            "880",
            "ACGT" * 120,
        ),
        _blast_row(
            "arcC_2",
            "contig1",
            "95.833",
            "480",
            "480",
            "1",
            "480",
            "999",
            "520",
            "700",
            "ACGT" * 120,
        ),
        _blast_row(
            "arcC_3",
            "contig3",
            "95.833",
            "300",
            "480",
            "1",
            "300",
            "10",
            "309",
            "500",
            "ACGT" * 75,
        ),
        _blast_row(
            "aroE_5",
            "contig1",
            "100.000",
            "450",
            "450",
            "1",
            "450",
            "2000",
            "2449",
            "850",
            "ACGT" * 112,
        ),
        _blast_row(
            "aroE_5",
            "contig2",
            "100.000",
            "200",
            "450",
            "1",
            "200",
            "3000",
            "3199",
            "400",
            "ACGT" * 50,
        ),
        _blast_row(
            "glpF_1",
            "contig1",
            "100.000",
            "400",
            "400",
            "1",
            "400",
            "4000",
            "4399",
            "800",
            "ACGT" * 100,
        ),
        _blast_row(
            "adk_7",
            "contigA",
            "98.000",
            "400",
            "400",
            "1",
            "400",
            "50",
            "449",
            "600",
            "ACGT" * 100,
        ),
        _blast_row(
            "adk_7",
            "contigB",
            "98.000",
            "400",
            "400",
            "1",
            "400",
            "60",
            "459",
            "600",
            "ACGT" * 100,
        ),
    ]
    path.write_text("\n".join(rows) + "\n")


CONTIGS = {
    name: "ACGT" * n
    for name, n in [
        ("ctg1", 12500),
        ("ctg2", 20000),
        ("ctg3", 15000),
        ("ctg4", 10000),
        ("ctg5", 17500),
    ]
}


def _paf_row(
    qname: str,
    qlen: str,
    qstart: str,
    qend: str,
    strand: str,
    tname: str,
    tlen: str,
    tstart: str,
    tend: str,
    nmatch: str,
    blen: str,
    mapq: str,
    nm: str,
) -> str:
    return "\t".join(
        [
            qname,
            qlen,
            qstart,
            qend,
            strand,
            tname,
            tlen,
            tstart,
            tend,
            nmatch,
            blen,
            mapq,
            f"NM:i:{nm}",
        ]
    )


def _write_paf_fixture(path: Path) -> None:
    rows = [
        _paf_row(
            "abcZ_1",
            "480",
            "0",
            "480",
            "+",
            "ctg1",
            "50000",
            "100",
            "580",
            "480",
            "480",
            "60",
            "0",
        ),
        _paf_row(
            "abcZ_1",
            "480",
            "0",
            "480",
            "+",
            "ctg2",
            "80000",
            "500",
            "980",
            "476",
            "480",
            "60",
            "4",
        ),
        _paf_row(
            "abcZ_2",
            "480",
            "0",
            "400",
            "-",
            "ctg1",
            "50000",
            "5000",
            "5400",
            "390",
            "400",
            "30",
            "10",
        ),
        _paf_row(
            "abcZ_3",
            "480",
            "0",
            "300",
            "+",
            "ctg3",
            "60000",
            "700",
            "1000",
            "290",
            "300",
            "20",
            "10",
        ),
        _paf_row(
            "adk_9",
            "448",
            "0",
            "448",
            "+",
            "ctg1",
            "50000",
            "9000",
            "9448",
            "448",
            "448",
            "60",
            "0",
        ),
        _paf_row(
            "adk_9",
            "450",
            "0",
            "220",
            "-",
            "ctg4",
            "40000",
            "120",
            "340",
            "215",
            "220",
            "40",
            "5",
        ),
        _paf_row(
            "unknownLocus_1",
            "400",
            "0",
            "400",
            "+",
            "ctg1",
            "50000",
            "15000",
            "15400",
            "400",
            "400",
            "60",
            "0",
        ),
        _paf_row(
            "aroE_2",
            "500",
            "0",
            "500",
            "+",
            "ctg5",
            "70000",
            "80",
            "580",
            "495",
            "500",
            "55",
            "5",
        ),
        _paf_row(
            "aroE_2",
            "500",
            "0",
            "500",
            "+",
            "ctg5",
            "70000",
            "80",
            "580",
            "495",
            "500",
            "55",
            "5",
        ),
        _paf_row(
            "aroE_2",
            "500",
            "0",
            "248",
            "-",
            "ctg2",
            "80000",
            "2216",
            "2464",
            "245",
            "248",
            "25",
            "5",
        ),
    ]
    path.write_text("\n".join(rows) + "\n")


def _assert_rows(actual: list, expected: list[dict]) -> None:
    """Compare parsed AlleleMatch rows against expected literals.

    Every dataclass field is asserted.  ``seq_len`` entries assert
    ``len(sequence)`` with the content locked to whole ``"ACGT"`` repeats
    (all fixture sequences are such repeats, which are
    reverse-complement invariant).
    """
    assert len(actual) == len(expected), (len(actual), len(expected))
    for row, want in zip(actual, expected, strict=True):
        assert is_dataclass(row)
        seq_len = want.pop("seq_len", None)
        for name in [f.name for f in fields(row)]:
            if name == "sequence":
                continue
            assert getattr(row, name) == want.get(name), (row.locus, name)
        if seq_len is None:
            assert row.sequence is None, (row.locus, row.sequence)
        else:
            assert row.sequence == "ACGT" * (seq_len // 4), (row.locus, seq_len)


def test_blastn_parser_golden(tmp_path: Path) -> None:
    fixture = tmp_path / "hits.tsv"
    _write_blast_fixture(fixture)
    matches, fragments = _parse_blast_output(fixture, LOCI, count_same_copy=True)

    expected_matches = [
        {
            "locus": "arcC",
            "allele_id": "1",
            "identity": 100.0,
            "coverage": 1.0,
            "strand": "+",
            "score": 900.0,
            "alignment_length": 480,
            "copy_count": 2,
            "query_contig": "contig1",
            "query_start": 100,
            "query_end": 579,
            "seq_len": 480,
        },
        {
            "locus": "arcC",
            "allele_id": "2",
            "identity": 95.833,
            "coverage": 1.0,
            "strand": "-",
            "score": 700.0,
            "alignment_length": 480,
            "copy_count": 1,
            "query_contig": "contig1",
            "query_start": 520,
            "query_end": 999,
            "seq_len": 480,
        },
        {
            "locus": "arcC",
            "allele_id": "3",
            "identity": 95.833,
            "coverage": 0.625,
            "strand": "+",
            "score": 500.0,
            "alignment_length": 300,
            "copy_count": 1,
            "query_contig": "contig3",
            "query_start": 10,
            "query_end": 309,
            "seq_len": 300,
        },
        {
            "locus": "aroE",
            "allele_id": "5",
            "identity": 100.0,
            "coverage": 1.0,
            "strand": "+",
            "score": 850.0,
            "alignment_length": 450,
            "copy_count": 2,
            "query_contig": "contig1",
            "query_start": 2000,
            "query_end": 2449,
            "seq_len": 448,
        },
        {
            "locus": "adk",
            "allele_id": "7",
            "identity": 98.0,
            "coverage": 1.0,
            "strand": "+",
            "score": 600.0,
            "alignment_length": 400,
            "copy_count": 2,
            "query_contig": "contigA",
            "query_start": 50,
            "query_end": 449,
            "seq_len": 400,
        },
    ]
    expected_fragments = [
        {
            "copy_count": 1,
            "locus": "arcC",
            "allele_id": "1",
            "identity": 100.0,
            "coverage": 1.0,
            "strand": "+",
            "score": 900.0,
            "alignment_length": 480,
            "query_contig": "contig1",
            "query_start": 100,
            "query_end": 579,
            "allele_length": 480,
            "allele_start": 0,
            "allele_end": 480,
            "seq_len": 480,
        },
        {
            "copy_count": 1,
            "locus": "arcC",
            "allele_id": "1",
            "identity": 99.792,
            "coverage": 1.0,
            "strand": "+",
            "score": 880.0,
            "alignment_length": 480,
            "query_contig": "contig2",
            "query_start": 500,
            "query_end": 979,
            "allele_length": 480,
            "allele_start": 0,
            "allele_end": 480,
            "seq_len": 480,
        },
        {
            "copy_count": 1,
            "locus": "arcC",
            "allele_id": "2",
            "identity": 95.833,
            "coverage": 1.0,
            "strand": "-",
            "score": 700.0,
            "alignment_length": 480,
            "query_contig": "contig1",
            "query_start": 520,
            "query_end": 999,
            "allele_length": 480,
            "allele_start": 0,
            "allele_end": 480,
            "seq_len": 480,
        },
        {
            "copy_count": 1,
            "locus": "arcC",
            "allele_id": "3",
            "identity": 95.833,
            "coverage": 0.625,
            "strand": "+",
            "score": 500.0,
            "alignment_length": 300,
            "query_contig": "contig3",
            "query_start": 10,
            "query_end": 309,
            "allele_length": 480,
            "allele_start": 0,
            "allele_end": 300,
            "seq_len": 300,
        },
        {
            "copy_count": 1,
            "locus": "aroE",
            "allele_id": "5",
            "identity": 100.0,
            "coverage": 1.0,
            "strand": "+",
            "score": 850.0,
            "alignment_length": 450,
            "query_contig": "contig1",
            "query_start": 2000,
            "query_end": 2449,
            "allele_length": 450,
            "allele_start": 0,
            "allele_end": 450,
            "seq_len": 448,
        },
        {
            "copy_count": 1,
            "locus": "aroE",
            "allele_id": "5",
            "identity": 100.0,
            "coverage": 0.4444444444444444,
            "strand": "+",
            "score": 400.0,
            "alignment_length": 200,
            "query_contig": "contig2",
            "query_start": 3000,
            "query_end": 3199,
            "allele_length": 450,
            "allele_start": 0,
            "allele_end": 200,
            "seq_len": 200,
        },
        {
            "copy_count": 1,
            "locus": "adk",
            "allele_id": "7",
            "identity": 98.0,
            "coverage": 1.0,
            "strand": "+",
            "score": 600.0,
            "alignment_length": 400,
            "query_contig": "contigA",
            "query_start": 50,
            "query_end": 449,
            "allele_length": 400,
            "allele_start": 0,
            "allele_end": 400,
            "seq_len": 400,
        },
        {
            "copy_count": 1,
            "locus": "adk",
            "allele_id": "7",
            "identity": 98.0,
            "coverage": 1.0,
            "strand": "+",
            "score": 600.0,
            "alignment_length": 400,
            "query_contig": "contigB",
            "query_start": 60,
            "query_end": 459,
            "allele_length": 400,
            "allele_start": 0,
            "allele_end": 400,
            "seq_len": 400,
        },
    ]
    _assert_rows(matches, [dict(e) for e in expected_matches])
    _assert_rows(fragments, expected_fragments)
    # blastn best rows include the aligned sequence; fragments carry allele
    # coordinates while best rows do not (schema locked).
    assert all(m.sequence is not None for m in matches)
    assert all(f.allele_start is not None for f in fragments)


def test_minimap2_parser_golden(tmp_path: Path) -> None:
    fixture = tmp_path / "hits.paf"
    _write_paf_fixture(fixture)
    matches, fragments = _parse_paf(fixture, LOCI, CONTIGS)

    expected_matches = [
        {
            "copy_count": 1,
            "locus": "abcZ",
            "allele_id": "1",
            "identity": 100.0,
            "coverage": 1.0,
            "strand": "+",
            "score": 100.0,
            "alignment_length": 480,
            "query_contig": "ctg1",
            "query_contig_length": 50000,
            "query_start": 100,
            "query_end": 580,
            "allele_length": 480,
            "allele_start": 0,
            "allele_end": 480,
        },
        {
            "copy_count": 1,
            "locus": "abcZ",
            "allele_id": "2",
            "identity": 97.5,
            "coverage": 0.8333333333333334,
            "strand": "-",
            "score": 81.25,
            "alignment_length": 400,
            "query_contig": "ctg1",
            "query_contig_length": 50000,
            "query_start": 5000,
            "query_end": 5400,
            "allele_length": 480,
            "allele_start": 0,
            "allele_end": 400,
        },
        {
            "copy_count": 1,
            "locus": "abcZ",
            "allele_id": "3",
            "identity": 96.66666666666667,
            "coverage": 0.625,
            "strand": "+",
            "score": 60.41666666666667,
            "alignment_length": 300,
            "query_contig": "ctg3",
            "query_contig_length": 60000,
            "query_start": 700,
            "query_end": 1000,
            "allele_length": 480,
            "allele_start": 0,
            "allele_end": 300,
        },
        {
            "copy_count": 1,
            "locus": "adk",
            "allele_id": "9",
            "identity": 100.0,
            "coverage": 1.0,
            "strand": "+",
            "score": 100.0,
            "alignment_length": 448,
            "query_contig": "ctg1",
            "query_contig_length": 50000,
            "query_start": 9000,
            "query_end": 9448,
            "allele_length": 448,
            "allele_start": 0,
            "allele_end": 448,
        },
        {
            "copy_count": 1,
            "locus": "aroE",
            "allele_id": "2",
            "identity": 99.0,
            "coverage": 1.0,
            "strand": "+",
            "score": 99.0,
            "alignment_length": 500,
            "query_contig": "ctg5",
            "query_contig_length": 70000,
            "query_start": 80,
            "query_end": 580,
            "allele_length": 500,
            "allele_start": 0,
            "allele_end": 500,
        },
    ]
    expected_fragments = [
        {
            "copy_count": 1,
            "locus": "abcZ",
            "allele_id": "1",
            "identity": 100.0,
            "coverage": 1.0,
            "strand": "+",
            "score": 100.0,
            "alignment_length": 480,
            "query_contig": "ctg1",
            "query_contig_length": 50000,
            "query_start": 100,
            "query_end": 580,
            "allele_length": 480,
            "allele_start": 0,
            "allele_end": 480,
            "seq_len": 480,
        },
        {
            "copy_count": 1,
            "locus": "abcZ",
            "allele_id": "1",
            "identity": 99.16666666666667,
            "coverage": 1.0,
            "strand": "+",
            "score": 99.16666666666667,
            "alignment_length": 480,
            "query_contig": "ctg2",
            "query_contig_length": 80000,
            "query_start": 500,
            "query_end": 980,
            "allele_length": 480,
            "allele_start": 0,
            "allele_end": 480,
            "seq_len": 480,
        },
        {
            "copy_count": 1,
            "locus": "abcZ",
            "allele_id": "2",
            "identity": 97.5,
            "coverage": 0.8333333333333334,
            "strand": "-",
            "score": 81.25,
            "alignment_length": 400,
            "query_contig": "ctg1",
            "query_contig_length": 50000,
            "query_start": 5000,
            "query_end": 5400,
            "allele_length": 480,
            "allele_start": 0,
            "allele_end": 400,
            "seq_len": 400,
        },
        {
            "copy_count": 1,
            "locus": "abcZ",
            "allele_id": "3",
            "identity": 96.66666666666667,
            "coverage": 0.625,
            "strand": "+",
            "score": 60.41666666666667,
            "alignment_length": 300,
            "query_contig": "ctg3",
            "query_contig_length": 60000,
            "query_start": 700,
            "query_end": 1000,
            "allele_length": 480,
            "allele_start": 0,
            "allele_end": 300,
            "seq_len": 300,
        },
        {
            "copy_count": 1,
            "locus": "adk",
            "allele_id": "9",
            "identity": 100.0,
            "coverage": 1.0,
            "strand": "+",
            "score": 100.0,
            "alignment_length": 448,
            "query_contig": "ctg1",
            "query_contig_length": 50000,
            "query_start": 9000,
            "query_end": 9448,
            "allele_length": 448,
            "allele_start": 0,
            "allele_end": 448,
            "seq_len": 448,
        },
        {
            "copy_count": 1,
            "locus": "adk",
            "allele_id": "9",
            "identity": 97.72727272727273,
            "coverage": 0.4888888888888889,
            "strand": "-",
            "score": 47.77777777777778,
            "alignment_length": 220,
            "query_contig": "ctg4",
            "query_contig_length": 40000,
            "query_start": 120,
            "query_end": 340,
            "allele_length": 450,
            "allele_start": 0,
            "allele_end": 220,
            "seq_len": 220,
        },
        {
            "copy_count": 1,
            "locus": "aroE",
            "allele_id": "2",
            "identity": 99.0,
            "coverage": 1.0,
            "strand": "+",
            "score": 99.0,
            "alignment_length": 500,
            "query_contig": "ctg5",
            "query_contig_length": 70000,
            "query_start": 80,
            "query_end": 580,
            "allele_length": 500,
            "allele_start": 0,
            "allele_end": 500,
            "seq_len": 500,
        },
        {
            "copy_count": 1,
            "locus": "aroE",
            "allele_id": "2",
            "identity": 99.0,
            "coverage": 1.0,
            "strand": "+",
            "score": 99.0,
            "alignment_length": 500,
            "query_contig": "ctg5",
            "query_contig_length": 70000,
            "query_start": 80,
            "query_end": 580,
            "allele_length": 500,
            "allele_start": 0,
            "allele_end": 500,
            "seq_len": 500,
        },
        {
            "copy_count": 1,
            "locus": "aroE",
            "allele_id": "2",
            "identity": 98.0,
            "coverage": 0.496,
            "strand": "-",
            "score": 48.608,
            "alignment_length": 248,
            "query_contig": "ctg2",
            "query_contig_length": 80000,
            "query_start": 2216,
            "query_end": 2464,
            "allele_length": 500,
            "allele_start": 0,
            "allele_end": 248,
            "seq_len": 248,
        },
    ]
    _assert_rows(matches, [dict(e) for e in expected_matches])
    _assert_rows(fragments, expected_fragments)
    # minimap2 best rows never carry a sequence (schema locked); fragment
    # sequences are allele-oriented contig slices, reverse-complemented on
    # the minus strand.
    assert all(m.sequence is None for m in matches)
    assert all(f.sequence is not None for f in fragments)
