from __future__ import annotations

import argparse
import csv
from collections import Counter
from pathlib import Path

BOUNDARY_REASONS = {"five_prime_boundary_shift", "three_prime_boundary_shift"}


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Create a normalization layer for chewBBACA vs gmlst allele "
            "discrepancies while preserving raw calls."
        )
    )
    parser.add_argument(
        "--concordance-diff",
        required=True,
        type=Path,
        help=(
            "TSV generated by scripts/analysis/cgmlst_concordance_report.py --output"
        ),
    )
    parser.add_argument(
        "--reason-table",
        required=False,
        type=Path,
        help="Boundary reason TSV (e.g. chewbbaca_vs_gmlst_numeric_diff_reason.tsv)",
    )
    parser.add_argument(
        "--anchor-side",
        choices=["reference", "query"],
        default="reference",
        help="Which side is authoritative for normalization (default: reference).",
    )
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--summary", required=False, type=Path)
    return parser.parse_args()


def _read_tsv(path: Path) -> list[dict[str, str]]:
    with path.open(newline="") as handle:
        reader = csv.DictReader(handle, delimiter="\t")
        rows = list(reader)
        if not reader.fieldnames:
            raise ValueError(f"No header found in TSV: {path}")
    return rows


def _strict_numeric(value: str) -> bool:
    return value.strip().isdigit()


def _is_missing_like(value: str) -> bool:
    return value.strip().upper() in {
        "",
        "-",
        "LNF",
        "NIPH",
        "ALM",
        "ASM",
        "PLOT3",
        "PLOT5",
        "LOTSC",
    }


def _is_non_exact_numeric(value: str) -> bool:
    cleaned = value.strip()
    return cleaned.startswith("~") and cleaned[1:].isdigit()


def _load_reason_index(path: Path | None) -> dict[str, dict[str, str]]:
    if path is None:
        return {}
    rows = _read_tsv(path)
    index: dict[str, dict[str, str]] = {}
    for row in rows:
        locus = row.get("locus", "").strip()
        if locus:
            index[locus] = row
    return index


def main() -> int:
    args = _parse_args()
    diff_rows = _read_tsv(args.concordance_diff)
    reason_index = _load_reason_index(args.reason_table)

    normalized_rows: list[dict[str, str]] = []
    decision_counts: Counter[str] = Counter()
    reason_counts: Counter[str] = Counter()

    for row in diff_rows:
        locus = row.get("locus", "").strip()
        query_raw = row.get("query_raw", "").strip()
        reference_raw = row.get("reference_raw", "").strip()

        reason_row = reason_index.get(locus)
        boundary_reason = ""
        boundary_subreason = ""
        if reason_row is not None:
            boundary_reason = reason_row.get("reason", "").strip()
            boundary_subreason = reason_row.get("subreason", "").strip()

        decision = "escalate"
        decision_reason = "unclassified_difference"
        normalized_call = ""

        if query_raw == reference_raw:
            decision = "unchanged"
            decision_reason = "raw_equal"
            normalized_call = query_raw
        elif _is_missing_like(query_raw) or _is_missing_like(reference_raw):
            decision = "escalate"
            decision_reason = "missing_or_special_class"
        elif (
            _strict_numeric(query_raw)
            and _strict_numeric(reference_raw)
            and query_raw != reference_raw
        ):
            if boundary_reason in BOUNDARY_REASONS:
                decision = "accept"
                decision_reason = (
                    f"boundary_shift::{boundary_reason}::{boundary_subreason}"
                )
                normalized_call = (
                    reference_raw if args.anchor_side == "reference" else query_raw
                )
            else:
                decision = "escalate"
                decision_reason = "strict_numeric_diff_without_boundary_evidence"
        elif _is_non_exact_numeric(query_raw) and _strict_numeric(reference_raw):
            if args.anchor_side == "reference":
                decision = "accept"
                decision_reason = "prodigal_anchor_reference_numeric_over_non_exact"
                normalized_call = reference_raw
            else:
                decision = "escalate"
                decision_reason = "non_exact_query_requires_manual_review"
        elif _strict_numeric(query_raw) and _is_non_exact_numeric(reference_raw):
            if args.anchor_side == "query":
                decision = "accept"
                decision_reason = "prodigal_anchor_query_numeric_over_non_exact"
                normalized_call = query_raw
            else:
                decision = "escalate"
                decision_reason = "non_exact_reference_requires_manual_review"
        else:
            decision = "escalate"
            decision_reason = "non_numeric_or_complex_difference"

        normalized_rows.append(
            {
                "locus": locus,
                "query_raw": query_raw,
                "reference_raw": reference_raw,
                "boundary_reason": boundary_reason,
                "boundary_subreason": boundary_subreason,
                "norm_decision": decision,
                "norm_reason": decision_reason,
                "norm_allele": normalized_call,
                "anchor_side": args.anchor_side,
            }
        )
        decision_counts[decision] += 1
        reason_counts[decision_reason] += 1

    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w", newline="") as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=[
                "locus",
                "query_raw",
                "reference_raw",
                "boundary_reason",
                "boundary_subreason",
                "norm_decision",
                "norm_reason",
                "norm_allele",
                "anchor_side",
            ],
            delimiter="\t",
        )
        writer.writeheader()
        writer.writerows(normalized_rows)

    print(f"rows\t{len(normalized_rows)}")
    for decision in sorted(decision_counts):
        print(f"decision::{decision}\t{decision_counts[decision]}")
    for reason in sorted(reason_counts):
        print(f"reason::{reason}\t{reason_counts[reason]}")

    if args.summary is not None:
        args.summary.parent.mkdir(parents=True, exist_ok=True)
        with args.summary.open("w", newline="") as handle:
            writer = csv.writer(handle, delimiter="\t")
            writer.writerow(["metric", "value"])
            writer.writerow(["rows", len(normalized_rows)])
            for decision in sorted(decision_counts):
                writer.writerow([f"decision::{decision}", decision_counts[decision]])
            for reason in sorted(reason_counts):
                writer.writerow([f"reason::{reason}", reason_counts[reason]])

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
