# Hard-coded scheme list from cgMLST.org (as of 2026-07)
# Source: https://www.cgmlst.org/ncs/1000
# Download URL: https://www.cgmlst.org/ncs/schema/{schema_id}/alleles/
# Note: schema_id no longer uses numeric suffixes (changed by cgMLST.org server)
_CGMLST_SCHEMES = [
    {
        "name": "Abaumannii",
        "schema_id": "Abaumannii",
        "display": "Acinetobacter baumannii cgMLST",
        "organism": "Acinetobacter baumannii",
        "loci": 2390,
    },
    {
        "name": "Banthracis",
        "schema_id": "Banthracis",
        "display": "Bacillus anthracis cgMLST",
        "organism": "Bacillus anthracis",
        "loci": 3803,
    },
    {
        "name": "Bpertussis",
        "schema_id": "Bpertussis",
        "display": "Bordetella pertussis cgMLST",
        "organism": "Bordetella pertussis",
        "loci": 2983,
    },
    {
        "name": "Bmelitensis",
        "schema_id": "Bmelitensis",
        "display": "Brucella melitensis cgMLST",
        "organism": "Brucella melitensis",
        "loci": 2704,
    },
    {
        "name": "Bspp",
        "schema_id": "Brucella",
        "display": "Brucella spp. cgMLST",
        "organism": "Brucella spp.",
        "loci": 1764,
    },
    {
        "name": "BmalleiFLI",
        "schema_id": "Bmallei_fli",
        "display": "Burkholderia mallei (FLI) cgMLST",
        "organism": "Burkholderia mallei",
        "loci": 2838,
    },
    {
        "name": "BmalleiRKI",
        "schema_id": "Bmallei_rki",
        "display": "Burkholderia mallei (RKI) cgMLST",
        "organism": "Burkholderia mallei",
        "loci": 3328,
    },
    {
        "name": "Bpseudomallei",
        "schema_id": "Bpseudomallei",
        "display": "Burkholderia pseudomallei cgMLST",
        "organism": "Burkholderia pseudomallei",
        "loci": 4221,
    },
    {
        "name": "Cjejunicoli",
        "schema_id": "Cjejuni_complex",
        "display": "Campylobacter jejuni/coli cgMLST",
        "organism": "Campylobacter jejuni/coli",
        "loci": 637,
    },
    {
        "name": "Cfreundii",
        "schema_id": "Cfreundii",
        "display": "Citrobacter freundii cgMLST",
        "organism": "Citrobacter freundii",
        "loci": 3250,
    },
    {
        "name": "Cfreundii2",
        "schema_id": "Cfreundii_complex",
        "display": "Citrobacter freundii/portucalensis/braakii/europaeus cgMLST",
        "organism": "Citrobacter freundii/portucalensis/braakii/europaeus",
        "loci": 2307,
    },
    {
        "name": "Cdifficile",
        "schema_id": "Cdifficile",
        "display": "Clostridioides difficile cgMLST",
        "organism": "Clostridioides difficile",
        "loci": 2147,
    },
    {
        "name": "Cperfringens",
        "schema_id": "Cperfringens",
        "display": "Clostridium perfringens cgMLST",
        "organism": "Clostridium perfringens",
        "loci": 1431,
    },
    {
        "name": "Cdiphtheriae",
        "schema_id": "Cdiphtheriae",
        "display": "Corynebacterium diphtheriae cgMLST",
        "organism": "Corynebacterium diphtheriae",
        "loci": 1553,
    },
    {
        "name": "Cpseudotuberculosis",
        "schema_id": "Cpseudotuberculosis",
        "display": "Corynebacterium pseudotuberculosis cgMLST",
        "organism": "Corynebacterium pseudotuberculosis",
        "loci": 1577,
    },
    {
        "name": "Csakazakii",
        "schema_id": "Csakazakii_complex",
        "display": "Cronobacter sakazakii/malonaticus cgMLST",
        "organism": "Cronobacter sakazakii/malonaticus",
        "loci": 2831,
    },
    {
        "name": "Ehormaechei",
        "schema_id": "Ehormaechei",
        "display": "Enterobacter hormaechei cgMLST",
        "organism": "Enterobacter hormaechei",
        "loci": 2178,
    },
    {
        "name": "Efaecalis",
        "schema_id": "Efaecalis",
        "display": "Enterococcus faecalis cgMLST",
        "organism": "Enterococcus faecalis",
        "loci": 1972,
    },
    {
        "name": "Efaecium",
        "schema_id": "Efaecium",
        "display": "Enterococcus faecium cgMLST",
        "organism": "Enterococcus faecium",
        "loci": 1423,
    },
    {
        "name": "Ecoli",
        "schema_id": "Ecoli",
        "display": "Escherichia coli cgMLST",
        "organism": "Escherichia coli",
        "loci": 2513,
    },
    {
        "name": "Ftularensis",
        "schema_id": "Ftularensis",
        "display": "Francisella tularensis cgMLST",
        "organism": "Francisella tularensis",
        "loci": 1147,
    },
    {
        "name": "Koxytoca",
        "schema_id": "Koxytoca_complex",
        "display": "Klebsiella oxytoca/grimontii/michiganensis/pasteurii cgMLST",
        "organism": "Klebsiella oxytoca/grimontii/michiganensis/pasteurii",
        "loci": 2536,
    },
    {
        "name": "Kpneumoniae",
        "schema_id": "Kpneumoniae_complex",
        "display": "Klebsiella pneumoniae/variicola/quasipneumoniae cgMLST",
        "organism": "Klebsiella pneumoniae/variicola/quasipneumoniae",
        "loci": 2358,
    },
    {
        "name": "Lpneumophila",
        "schema_id": "Lpneumophila",
        "display": "Legionella pneumophila cgMLST",
        "organism": "Legionella pneumophila",
        "loci": 1521,
    },
    {
        "name": "Lmonocytogenes",
        "schema_id": "Lmonocytogenes",
        "display": "Listeria monocytogenes cgMLST",
        "organism": "Listeria monocytogenes",
        "loci": 1701,
    },
    {
        "name": "Mmorganii",
        "schema_id": "Mmorganii",
        "display": "Morganella morganii cgMLST",
        "organism": "Morganella morganii",
        "loci": 2462,
    },
    {
        "name": "Mtuberculosis",
        "schema_id": "Mtuberculosis_complex",
        "display": "Mycobacterium tuberculosis/bovis/africanum/canettii cgMLST",
        "organism": "Mycobacterium tuberculosis/bovis/africanum/canettii",
        "loci": 2891,
    },
    {
        "name": "Mabscessus",
        "schema_id": "Mabscessus",
        "display": "Mycobacteroides abscessus cgMLST",
        "organism": "Mycobacteroides abscessus",
        "loci": 2904,
    },
    {
        "name": "Mgallisepticum",
        "schema_id": "Mgallisepticum",
        "display": "Mycoplasma gallisepticum cgMLST",
        "organism": "Mycoplasma gallisepticum",
        "loci": 425,
    },
    {
        "name": "Plarvae",
        "schema_id": "Plarvae",
        "display": "Paenibacillus larvae cgMLST",
        "organism": "Paenibacillus larvae",
        "loci": 2419,
    },
    {
        "name": "Pmirabilis",
        "schema_id": "Pmirabilis",
        "display": "Proteus mirabilis cgMLST",
        "organism": "Proteus mirabilis",
        "loci": 2574,
    },
    {
        "name": "Pstuartii",
        "schema_id": "Pstuartii",
        "display": "Providencia stuartii cgMLST",
        "organism": "Providencia stuartii",
        "loci": 3079,
    },
    {
        "name": "Paeruginosa",
        "schema_id": "Paeruginosa",
        "display": "Pseudomonas aeruginosa cgMLST",
        "organism": "Pseudomonas aeruginosa",
        "loci": 3867,
    },
    {
        "name": "Senterica",
        "schema_id": "Senterica",
        "display": "Salmonella enterica cgMLST",
        "organism": "Salmonella enterica",
        "loci": 3002,
    },
    {
        "name": "Smarcescens",
        "schema_id": "Smarcescens",
        "display": "Serratia marcescens cgMLST",
        "organism": "Serratia marcescens",
        "loci": 2692,
    },
    {
        "name": "Sargenteus",
        "schema_id": "Sargenteus",
        "display": "Staphylococcus argenteus cgMLST",
        "organism": "Staphylococcus argenteus",
        "loci": 2168,
    },
    {
        "name": "Saureus",
        "schema_id": "Saureus",
        "display": "Staphylococcus aureus cgMLST",
        "organism": "Staphylococcus aureus",
        "loci": 1861,
    },
    {
        "name": "Scapitis",
        "schema_id": "Scapitis",
        "display": "Staphylococcus capitis cgMLST",
        "organism": "Staphylococcus capitis",
        "loci": 1492,
    },
    {
        "name": "Spyogenes",
        "schema_id": "Spyogenes",
        "display": "Streptococcus pyogenes cgMLST",
        "organism": "Streptococcus pyogenes",
        "loci": 1095,
    },
    {
        "name": "Yenterocolitica",
        "schema_id": "Yenterocolitica",
        "display": "Yersinia enterocolitica cgMLST",
        "organism": "Yersinia enterocolitica",
        "loci": 2582,
    },
]
